In [8]:
import pandas as pd

In [9]:
pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue')

[    Rank                  Name                    Industry  \
 0      1               Walmart                      Retail
 1      2                Amazon  Retail and cloud computing
 2      3                 Apple        Electronics industry
 3      4    UnitedHealth Group                  Healthcare
 4      5    Berkshire Hathaway                Conglomerate
 ..   ...                   ...                         ...
 95    96                  TIAA                  Financials
 96    97                   CHS     Agriculture cooperative
 97    98  Bristol-Myers Squibb     Pharmaceutical industry
 98    99  Dow Chemical Company           Chemical industry
 99   100              Best Buy                      Retail

     Revenue (USD millions) Revenue growth  Employees  \
 0                   648125           6.0%    2100000
 1                   574785          11.9%    1525000
 2                   383482          -2.8%     161000
 3                   371622          14.6%     440000
 4                   364482          20.7%     396500
 ..                     ...            ...        ...
 95                   45735          11.8%      16023
 96                   45590          -4.6%      10609
 97                   45006          -2.5%      34100
 98                   44622         -21.6%      35900
 99                   43452          -6.1%      85000

                       Headquarters
 0            Bentonville, Arkansas
 1              Seattle, Washington
 2            Cupertino, California
 3            Minnetonka, Minnesota
 4                  Omaha, Nebraska
 ..                             ...
 95         New York City, New York
 96  Inver Grove Heights, Minnesota
 97         New York City, New York
 98               Midland, Michigan
 99            Richfield, Minnesota

 [100 rows x 7 columns],
    Rank                                Name                       Industry  \
 0     1                             Cargill                  Food industry
 1     2                     Koch Industries                   Conglomerate
 2     3                Publix Super Markets                         Retail
 3     4                  Mars, Incorporated                  Food industry
 4     5                               H-E-B                         Retail
 5     6                      Reyes Holdings                    Wholesaling
 6     7                 Enterprise Holdings                     Car rental
 7     8               C&S Wholesale Grocers                    Wholesaling
 8     9                              Love's  Petroleum industry and Retail
 9    10  Southern Glazer's Wine and Spirits                  Food industry

    Revenue (USD billions)  Employees             Headquarters
 0                   177.0     160000    Minnetonka, Minnesota
 1                   125.0     120000          Wichita, Kansas
 2                    54.5     250000    Winter Haven, Florida
 3                    47.0     140000         McLean, Virginia
 4                    43.6     145000       San Antonio, Texas
 5                    40.0      36000       Rosemont, Illinois
 6                    35.0      90000        Clayton, Missouri
 7                    34.7      15000     Keene, New Hampshire
 8                    26.5      40000  Oklahoma City, Oklahoma
 9                    26.0      24000         Miramar, Florida  ,
    Rank                Name                 Industry  Profits (USD millions)
 0     1               Apple              Electronics                   96995
 1     2  Berkshire Hathaway             Conglomerate                   96223
 2     3            Alphabet               Technology                   73795
 3     4           Microsoft               Technology                   72361
 4     5      JPMorgan Chase               Financials                   49552
 5     6      Meta Platforms               Technology                   39098
 6     7          ExxonMobil       Petroleum industry                   36010
 7     8   Johnson & Johnson  Pharmaceutical industry                   35153
 8     9              Amazon        Retail/Technology                   30425
 9    10              Nvidia               Technology                   29760]

In [10]:
pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue')[0]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,648125,6.0%,2100000,"Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,574785,11.9%,1525000,"Seattle, Washington"
2,3,Apple,Electronics industry,383482,-2.8%,161000,"Cupertino, California"
3,4,UnitedHealth Group,Healthcare,371622,14.6%,440000,"Minnetonka, Minnesota"
4,5,Berkshire Hathaway,Conglomerate,364482,20.7%,396500,"Omaha, Nebraska"
...,...,...,...,...,...,...,...
95,96,TIAA,Financials,45735,11.8%,16023,"New York City, New York"
96,97,CHS,Agriculture cooperative,45590,-4.6%,10609,"Inver Grove Heights, Minnesota"
97,98,Bristol-Myers Squibb,Pharmaceutical industry,45006,-2.5%,34100,"New York City, New York"
98,99,Dow Chemical Company,Chemical industry,44622,-21.6%,35900,"Midland, Michigan"
99,100,Best Buy,Retail,43452,-6.1%,85000,"Richfield, Minnesota"

In [11]:
pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue')[1]

,Rank,Name,Industry,Revenue (USD billions),Employees,Headquarters
0,1,Cargill,Food industry,177.0,160000,"Minnetonka, Minnesota"
1,2,Koch Industries,Conglomerate,125.0,120000,"Wichita, Kansas"
2,3,Publix Super Markets,Retail,54.5,250000,"Winter Haven, Florida"
3,4,"Mars, Incorporated",Food industry,47.0,140000,"McLean, Virginia"
4,5,H-E-B,Retail,43.6,145000,"San Antonio, Texas"
5,6,Reyes Holdings,Wholesaling,40.0,36000,"Rosemont, Illinois"
6,7,Enterprise Holdings,Car rental,35.0,90000,"Clayton, Missouri"
7,8,C&S Wholesale Grocers,Wholesaling,34.7,15000,"Keene, New Hampshire"
8,9,Love's,Petroleum industry and Retail,26.5,40000,"Oklahoma City, Oklahoma"
9,10,Southern Glazer's Wine and Spirits,Food industry,26.0,24000,"Miramar, Florida"

In [12]:
pd.read_html('https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue')[2]

   Rank                Name                 Industry  Profits (USD millions)
0     1               Apple              Electronics                   96995
1     2  Berkshire Hathaway             Conglomerate                   96223
2     3            Alphabet               Technology                   73795
3     4           Microsoft               Technology                   72361
4     5      JPMorgan Chase               Financials                   49552
5     6      Meta Platforms               Technology                   39098
6     7          ExxonMobil       Petroleum industry                   36010
7     8   Johnson & Johnson  Pharmaceutical industry                   35153
8     9              Amazon        Retail/Technology                   30425
9    10              Nvidia               Technology                   29760